# Generated by Django 5.1.1 on 2026-08-10 18:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatgpt', '0010_chatgptaccount_archived_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_assignments', to='chatgpt.chatgptaccount')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_assignments', to='chatgpt.chatgptcar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-assigned_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_no', models.CharField(db_index=True, max_length=40, unique=True)),
                ('order_type', models.CharField(choices=[('PURCHASE', '新购'), ('RENEW', '续费'), ('UPGRADE', '升级'), ('DOWNGRADE', '降级')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', '待支付'), ('PAID', '已支付'), ('CLOSED', '已关闭'), ('FAILED', '支付失败'), ('REFUNDED', '已退款')], db_index=True, default='PENDING', max_length=16)),
                ('provider', models.CharField(default='manual', max_length=32)),
                ('provider_order_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(blank=True, max_length=96, null=True, unique=True)),
                ('plan_snapshot', models.JSONField(default=dict)),
                ('offer_snapshot', models.JSONField(default=dict)),
                ('price_cents', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='CNY', max_length=8)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=128)),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(max_length=32)),
                ('amount_cents', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='CNY', max_length=8)),
                ('signature_verified', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='billing.order')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('pool_tier', models.CharField(choices=[('STANDARD', '普通 Plus 池'), ('PREMIUM', '高级 Plus 池')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_plans', to='chatgpt.chatgptcar')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='billing.plan'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('category', models.CharField(default='NOTICE', max_length=32)),
                ('severity', models.CharField(default='INFO', max_length=16)),
                ('audience', models.CharField(choices=[('ALL', '全部用户'), ('ACTIVE_SUBSCRIBERS', '有效订阅用户'), ('PLAN', '指定套餐')], default='ALL', max_length=24)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='billing.plan')),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PlanOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=48)),
                ('name', models.CharField(max_length=64)),
                ('months', models.PositiveSmallIntegerField()),
                ('price_cents', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='CNY', max_length=8)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_purchase_enabled', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='billing.plan')),
            ],
            options={
                'ordering': ('months', 'price_cents', 'id'),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='billing.planoffer'),
        ),
        migrations.CreateModel(
            name='PoolAccountPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('STANDARD', '普通 Plus 池'), ('PREMIUM', '高级 Plus 池')], max_length=16)),
                ('binding_limit', models.PositiveSmallIntegerField(default=5)),
                ('enabled', models.BooleanField(default=True)),
                ('health_status', models.CharField(default='HEALTHY', max_length=16)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_policy', to='chatgpt.chatgptaccount')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_policies', to='chatgpt.chatgptcar')),
            ],
            options={
                'ordering': ('pool_id', 'account_id'),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', '待生效'), ('ACTIVE', '生效中'), ('SUSPENDED', '已暂停'), ('REFUNDED', '已退款'), ('EXPIRED', '已到期'), ('CANCELLED', '已取消')], db_index=True, default='PENDING', max_length=16)),
                ('source', models.CharField(default='manual', max_length=32)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('scheduled_months', models.PositiveSmallIntegerField(default=0)),
                ('auto_renew', models.BooleanField(default=False)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.planoffer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('scheduled_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_subscriptions', to='billing.planoffer')),
                ('scheduled_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_subscriptions', to='billing.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-ends_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PoolReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('HELD', '支付席位保留'), ('ACTIVE', '已购席位'), ('ASSIGNED', '已绑定账号'), ('RELEASED', '已释放'), ('EXPIRED', '已过期')], db_index=True, max_length=16)),
                ('slot_count', models.PositiveSmallIntegerField(default=1)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='billing.order')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='billing.plan')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_reservations', to='chatgpt.chatgptcar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_reservations', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='billing.subscription')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AccountAssignmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ASSIGNED', '首次分配'), ('MIGRATED', '故障迁移'), ('RELEASED', '释放')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='billing.accountassignment')),
                ('new_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_events_to', to='chatgpt.chatgptaccount')),
                ('old_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_events_from', to='chatgpt.chatgptaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_events', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_events', to='billing.subscription')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='accountassignment',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assignment', to='billing.subscription'),
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('result', models.CharField(choices=[('SUCCESS', '成功'), ('ERROR', '失败'), ('DENIED', '拒绝')], max_length=16)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('request_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='chatgpt.chatgptaccount')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='billing.plan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='billing.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-request_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='SYSTEM', max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('dedupe_key', models.CharField(blank=True, max_length=128)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='billing.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='planoffer',
            constraint=models.UniqueConstraint(fields=('plan', 'code'), name='billing_offer_plan_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='planoffer',
            constraint=models.CheckConstraint(condition=models.Q(('months__gte', 1)), name='billing_offer_months_positive'),
        ),
        migrations.AddConstraint(
            model_name='poolreservation',
            constraint=models.CheckConstraint(condition=models.Q(('slot_count', 1)), name='billing_reservation_one_slot'),
        ),
        migrations.AddConstraint(
            model_name='accountassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('user',), name='billing_one_active_assignment_per_user'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['user', 'request_at'], name='billing_usa_user_id_a78d37_idx'),
        ),
        migrations.AddConstraint(
            model_name='usernotification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('user', 'dedupe_key'), name='billing_notification_dedupe_uniq'),
        ),
    ]
