# Generated by Django 5.1.1 on 2026-08-11 04:27

from django.db import migrations, models


def normalize_duplicate_provider_transactions(apps, schema_editor):
    transaction_model = apps.get_model("billing", "PaymentTransaction")
    seen = set()
    for transaction in transaction_model.objects.order_by("id").iterator():
        provider_transaction_id = (transaction.provider_transaction_id or "").strip()
        if not provider_transaction_id:
            continue
        key = (transaction.provider, provider_transaction_id)
        if key in seen:
            transaction.provider_transaction_id = f"legacy-duplicate-{transaction.id}-{provider_transaction_id}"[:128]
            transaction.save(update_fields=["provider_transaction_id"])
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(normalize_duplicate_provider_transactions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_transaction_id', ''), _negated=True), fields=('provider', 'provider_transaction_id'), name='billing_provider_transaction_uniq'),
        ),
    ]
