# Generated by Django 5.1.1 on 2026-08-11 06:23

from django.db import migrations, models


def replace_legacy_plan_taglines(apps, schema_editor):
    Plan = apps.get_model("billing", "Plan")
    Plan.objects.filter(
        pool_tier="STANDARD",
        tagline__in=("5-8 人共享 Plus 号池", "5-8 人共享号池"),
    ).update(tagline="稳定的 Plus 号池服务")
    Plan.objects.filter(
        pool_tier="PREMIUM",
        tagline__in=("1-3 人 Plus 号池", "1-3 人号池"),
    ).update(tagline="高优先级 Plus 号池服务")


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_paymenttransaction_billing_provider_transaction_uniq'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('channel', models.CharField(max_length=32)),
                ('contact', models.CharField(max_length=240)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('qr_image', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.RunPython(replace_legacy_plan_taglines, migrations.RunPython.noop),
    ]
