# Generated by Django 5.1.1 on 2026-08-11 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_supportcontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['provider', 'status', 'payment_expires_at'], name='billing_order_pay_state_ix'),
        ),
    ]
