# Generated by Django 5.1.1 on 2026-08-12 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_order_entitlement_months(apps, schema_editor):
    Order = apps.get_model('billing', 'Order')
    for order in Order.objects.select_related('offer').iterator(chunk_size=500):
        months = (order.offer_snapshot or {}).get('months') or order.offer.months or 1
        try:
            months = max(int(months), 1)
        except (TypeError, ValueError):
            months = 1
        if order.entitlement_months != months:
            Order.objects.filter(pk=order.pk).update(entitlement_months=months)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alipay_payment_expiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='entitlement_months',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RunPython(backfill_order_entitlement_months, migrations.RunPython.noop),
        migrations.CreateModel(
            name='CommercialSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('redemption_enabled', models.BooleanField(default=False)),
                ('purchase_url', models.URLField(blank=True, max_length=500)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commercial_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'commercial settings',
            },
        ),
        migrations.CreateModel(
            name='RedemptionCodeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_no', models.CharField(db_index=True, max_length=32, unique=True)),
                ('plan_snapshot', models.JSONField(default=dict)),
                ('offer_snapshot', models.JSONField(default=dict)),
                ('entitlement_months', models.PositiveSmallIntegerField()),
                ('price_cents', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='CNY', max_length=8)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_redemption_batches', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemption_batches', to='billing.planoffer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemption_batches', to='billing.plan')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RedemptionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_no', models.CharField(db_index=True, max_length=32, unique=True)),
                ('key_version', models.CharField(max_length=32)),
                ('code_digest', models.CharField(max_length=64)),
                ('code_mask', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('AVAILABLE', '未使用'), ('REDEEMED', '已使用'), ('REVOKED', '已撤销')], db_index=True, default='AVAILABLE', max_length=16)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('redeemed_email', models.EmailField(blank=True, max_length=254)),
                ('redeemed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('redeemed_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('redeemed_user_agent', models.CharField(blank=True, max_length=512)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_redemption_codes', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redemption_code', to='billing.order')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redeemed_codes', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_redemption_codes', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redemption_codes', to='billing.subscription')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='billing.redemptioncodebatch')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='redemptioncodebatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 1000)), name='bill_red_batch_qty_range'),
        ),
        migrations.AddConstraint(
            model_name='redemptioncodebatch',
            constraint=models.CheckConstraint(condition=models.Q(('entitlement_months__gte', 1)), name='bill_red_batch_months_pos'),
        ),
        migrations.AddIndex(
            model_name='redemptioncode',
            index=models.Index(fields=['batch', 'status'], name='bill_red_code_batch_ix'),
        ),
        migrations.AddIndex(
            model_name='redemptioncode',
            index=models.Index(fields=['status', 'is_archived'], name='bill_red_code_state_ix'),
        ),
        migrations.AddIndex(
            model_name='redemptioncode',
            index=models.Index(fields=['redeemed_by', 'redeemed_at'], name='bill_red_user_time_ix'),
        ),
        migrations.AddConstraint(
            model_name='redemptioncode',
            constraint=models.UniqueConstraint(fields=('key_version', 'code_digest'), name='bill_red_code_digest_uniq'),
        ),
    ]
