"""
Django settings for chatgpt_mirror project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import logging.config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

DJANGO_ENV = os.environ.get("DJANGO_ENV", "LOCAL").upper()


def env_bool(key: str, default: bool) -> bool:
    value = os.environ.get(key)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(key: str, default: str) -> list[str]:
    value = os.environ.get(key, default)
    return [item.strip() for item in value.split(",") if item.strip()]


def required_env(key: str) -> str:
    value = os.environ.get(key, "").strip()
    if not value:
        raise RuntimeError(f"{key} must be set when DJANGO_ENV=PRODUCTION")
    return value


# SECURITY WARNING: keep the secret key used in production secret.
SECRET_KEY = (
    required_env("DJANGO_SECRET_KEY")
    if DJANGO_ENV == "PRODUCTION"
    else os.environ.get(
        "DJANGO_SECRET_KEY",
        "django-insecure-dev-only-change-me",
    )
)

ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    "django,localhost,127.0.0.1" if DJANGO_ENV == "PRODUCTION" else "*",
)
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS", "")
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", False)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", DJANGO_ENV == "PRODUCTION")
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", DJANGO_ENV == "PRODUCTION")
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "SAMEORIGIN"
REFERRER_POLICY = "same-origin"


# 开发时的日志配置，INFO 及以上级别的日志输出到 console。

if not os.path.exists(BASE_DIR + "/logs"):
    os.makedirs(BASE_DIR + "/logs")


if not os.path.exists(BASE_DIR + "/static"):
    os.makedirs(BASE_DIR + "/static")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": True,
    "formatters": {
        "simple": {
            "format": "[%(asctime)s] %(levelname)s [%(module)s|%(lineno)s] - %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {"level": "INFO", "class": "logging.StreamHandler", "formatter": "simple"},
        "default": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "formatter": "simple",
            "filename": BASE_DIR + "/logs/default.log",
            "when": "midnight",
            "interval": 1,
            "backupCount": 7,
        },
        "cron": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "formatter": "simple",
            "filename": BASE_DIR + "/logs/cron.log",
            "when": "midnight",
            "interval": 1,
            "backupCount": 7,
        },
        "errors": {
            "level": "WARNING",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "formatter": "simple",
            "filename": BASE_DIR + "/logs/errors.log",
            "when": "midnight",
            "interval": 1,
            "backupCount": 7,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "errors"],
            "propagate": "ERROR",
            "level": "INFO",
        },
        "cron":{
            "handlers": ["console", "cron", "errors"],
            "level": "INFO",
        },
        "default": {
            "handlers": ["console", "default", "errors"],
            "level": "INFO",
        },
    },
}

logging.config.dictConfig(LOGGING)
default_logger = logging.getLogger("default")

# Application definition

INSTALLED_APPS = [
    # "simpleui",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "app.accounts",
    "app.chatgpt",
    "app.billing",
    "django_crontab",
]

# django simpleui
# SIMPLEUI_HOME_INFO = False
# SIMPLEUI_HOME_QUICK = False
# SIMPLEUI_DEFAULT_THEME = "gray.css"


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "app.security.NoStoreApiMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

REST_FRAMEWORK = {
    "PAGE_SIZE": 10,
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "app.accounts.authentication.ExpiringCookieTokenAuthentication",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "login_ip": "20/min",
        "login_account": "10/min",
        "expensive_user": "30/min",
        "user": "120/min",
    },
}

API_TOKEN_TTL_SECONDS = int(os.environ.get("API_TOKEN_TTL_SECONDS", str(7 * 24 * 60 * 60)))

ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"

AUTH_USER_MODEL = "accounts.User"

logs_path = "{}/logs".format(BASE_DIR)
if not os.path.exists(logs_path):
    os.makedirs(logs_path)

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DB_PATH = "{}/db".format(BASE_DIR)
if not os.path.exists(DB_PATH):
    os.makedirs(DB_PATH)

DATABASE_ENGINE = os.environ.get("DATABASE_ENGINE", "sqlite").strip().lower()
if DATABASE_ENGINE in {"postgres", "postgresql"}:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "chatgpt_mirror"),
            "USER": os.environ.get("POSTGRES_USER", "chatgpt_mirror"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
            "HOST": os.environ.get("POSTGRES_HOST", "postgres"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
            "CONN_MAX_AGE": int(os.environ.get("POSTGRES_CONN_MAX_AGE", "60")),
            "OPTIONS": {"connect_timeout": 10},
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.environ.get("SQLITE_PATH", "{}/db.sqlite3".format(DB_PATH)),
        }
    }

MIGRATION_SOURCE_SQLITE_PATH = os.environ.get("MIGRATION_SOURCE_SQLITE_PATH", "").strip()
if MIGRATION_SOURCE_SQLITE_PATH:
    DATABASES["legacy_sqlite"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": MIGRATION_SOURCE_SQLITE_PATH,
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True

BILLING_ENABLED = env_bool("BILLING_ENABLED", False)
BILLING_ENFORCE_SUBSCRIPTION = env_bool("BILLING_ENFORCE_SUBSCRIPTION", False)
BILLING_MOCK_PAYMENTS = env_bool("BILLING_MOCK_PAYMENTS", False)
PAYMENT_PROVIDER = os.environ.get("PAYMENT_PROVIDER", "manual").strip().lower()
BILLING_ORDER_HOLD_MINUTES = int(os.environ.get("BILLING_ORDER_HOLD_MINUTES", "30"))
PAYMENT_CALLBACK_MAX_AGE_SECONDS = int(os.environ.get("PAYMENT_CALLBACK_MAX_AGE_SECONDS", "900"))
PAYMENT_CALLBACK_MAX_FUTURE_SKEW_SECONDS = int(
    os.environ.get("PAYMENT_CALLBACK_MAX_FUTURE_SKEW_SECONDS", "300")
)
PAYMENT_CALLBACK_LOCK_ENABLED = env_bool(
    "PAYMENT_CALLBACK_LOCK_ENABLED",
    DJANGO_ENV == "PRODUCTION",
)

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://redis:6379/1")
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = int(os.environ.get("CELERY_TASK_TIME_LIMIT", "300"))
CELERY_TASK_ALWAYS_EAGER = env_bool("CELERY_TASK_ALWAYS_EAGER", False)
CELERY_BEAT_SCHEDULE = {
    "billing-expire-reservations-every-five-minutes": {
        "task": "app.billing.tasks.expire_stale_reservations_task",
        "schedule": 300.0,
    },
    "billing-maintenance-every-hour": {
        "task": "app.billing.tasks.subscription_maintenance_task",
        "schedule": 3600.0,
    },
    "billing-expiry-reminders-daily": {
        "task": "app.billing.tasks.expiry_reminders_task",
        "schedule": 86400.0,
    },
    "billing-account-health-every-fifteen-minutes": {
        "task": "app.billing.tasks.account_health_task",
        "schedule": 900.0,
    },
}

EMAIL_NOTIFICATIONS_ENABLED = env_bool("EMAIL_NOTIFICATIONS_ENABLED", False)
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "465"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", True)
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", False)
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "15"))
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "noreply@localhost")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

if DJANGO_ENV == "PRODUCTION":
    # 生产环境
    print("PRODUCTION environment")
    from app.config.production import *


else:  # if DJANGO_ENV == "LOCAL":
    # 本地开发 环境
    print("local environment")
    from app.config.local import *
