# Generated by Django 5.1.1 on 2026-08-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0009_encrypt_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgptaccount',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归档时间'),
        ),
        migrations.AddField(
            model_name='chatgptaccount',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='已归档'),
        ),
    ]
